### ISSUE TITLE
 Failed to load extension

### ISSUE THREAD

**Issue by stephancill** [agustif/twitter-zero#1]
After downloading the source code and attempting to load it unpacked, I get the following error:

```
Could not load icon 'logo-16.png' specified in 'action'.
```

<img width="532" alt="Screenshot 2023-04-19 at 11 56 04" src="https://user-images.githubusercontent.com/5469870/233040636-894daf90-d544-4ae0-9baf-af0ee22e41e8.png">

I changed the action key in the manifest to the following and that fixed it:

```
"action": {
    "default_icon": {
      "16": "assets/logo-16.png",
      "32": "assets/logo-32.png",
      "48": "assets/logo-48.png",
      "128": "assets/logo-128.png"
    },
    "default_title": "Zero Twitter"
  }
```

**Comment by agustif** [comment]
> After downloading the source code and attempting to load it unpacked, I get the following error:
> 
> 
> 
> ```
> 
> Could not load icon 'logo-16.png' specified in 'action'.
> 
> ```
> 
> 
> 
> <img width="532" alt="Screenshot 2023-04-19 at 11 56 04" src="https://user-images.githubusercontent.com/5469870/233040636-894daf90-d544-4ae0-9baf-af0ee22e41e8.png">
> 
> 
> 
> 
> 
> I changed the action key in the manifest to the following and that fixed it:
> 
> 
> 
> ```
> 
> "action": {
> 
>     "default_icon": {
> 
>       "16": "assets/logo-16.png",
> 
>       "32": "assets/logo-32.png",
> 
>       "48": "assets/logo-48.png",
> 
>       "128": "assets/logo-128.png"
> 
>     },
> 
>     "default_title": "Zero Twitter"
> 
>   }
> 
> ```

Thank you Stephan, will fix now somehow missed to push the updated icons!

**Comment by agustif** [comment]
fixed on latest

https://github.com/agustif/twitter-zero/releases/tag/v1.0

Thank you!
